# Generated by Django 2.1.4 on 2018-12-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('family', models.IntegerField()),
                ('fare', models.IntegerField()),
            ],
            options={
                'db_table': 'titanic',
            },
        ),
    ]
