# Generated by Django 2.1.4 on 2019-01-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titanic_cls', '0002_titanic_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titanic',
            name='family',
            field=models.CharField(default='NaN', max_length=10),
        ),
    ]
